// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Payment_Module.DiuSac
{
    public partial class DIU_SACContext : DbContext
    {
        public DIU_SACContext()
        {
        }

        public DIU_SACContext(DbContextOptions<DIU_SACContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationType> ApplicationType { get; set; }
        public virtual DbSet<Student> Student { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Application>(entity =>
            {
                entity.HasIndex(e => e.RowVersion, "IX_Application")
                    .IsUnique();

                entity.Property(e => e.Id).HasMaxLength(36);

                entity.Property(e => e.AccountsDecision).HasMaxLength(10);

                entity.Property(e => e.ApplicationBody).IsRequired();

                entity.Property(e => e.ApplicationStatusId)
                    .IsRequired()
                    .HasMaxLength(36);

                entity.Property(e => e.ApplicationTypeId)
                    .IsRequired()
                    .HasMaxLength(36);

                entity.Property(e => e.AppliedOn).HasColumnType("datetime");

                entity.Property(e => e.CampusId).HasMaxLength(50);

                entity.Property(e => e.CoordinationOfficeDecision).HasMaxLength(10);

                entity.Property(e => e.ExamDecision).HasMaxLength(10);

                entity.Property(e => e.RowVersion)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.SemesterId).HasMaxLength(50);

                entity.Property(e => e.StudentId)
                    .IsRequired()
                    .HasMaxLength(15);

                entity.Property(e => e.UpdatedBy).HasMaxLength(10);

                entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

                entity.HasOne(d => d.ApplicationType)
                    .WithMany(p => p.Application)
                    .HasForeignKey(d => d.ApplicationTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Application_ApplicationType");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.Application)
                    .HasForeignKey(d => d.StudentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Application_Student");
            });

            modelBuilder.Entity<ApplicationType>(entity =>
            {
                entity.HasIndex(e => e.Name, "IX_ApplicationType")
                    .IsUnique();

                entity.Property(e => e.Id).HasMaxLength(36);

                entity.Property(e => e.ApplicationFee).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.ApplicationToAddressing)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Description).HasMaxLength(2000);

                entity.Property(e => e.DummyApllicationBody).HasMaxLength(2000);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(150);
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.Property(e => e.Id).HasMaxLength(15);

                entity.Property(e => e.CampusId).HasMaxLength(50);

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.FacultyId).HasMaxLength(50);

                entity.Property(e => e.FatherMobile).HasMaxLength(50);

                entity.Property(e => e.LocalGuardianMobile).HasMaxLength(50);

                entity.Property(e => e.MentorId).HasMaxLength(10);

                entity.Property(e => e.Mobile).HasMaxLength(50);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PassOutSemester).HasMaxLength(50);

                entity.Property(e => e.ProgramId).HasMaxLength(50);

                entity.Property(e => e.SemesterId).HasMaxLength(50);

                entity.Property(e => e.ShiftId).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
