// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment_Module.Models;

namespace Payment_Module.Migrations
{
    [DbContext(typeof(PaymentDBContext))]
    [Migration("20220313083038_Payment Response Table")]
    partial class PaymentResponseTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Payment_Module.Models.PaymentResponse", b =>
                {
                    b.Property<string>("reff_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("APIConnect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("account_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("bank_tran_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("base_fair")
                        .HasColumnType("float");

                    b.Property<string>("card_brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("card_issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("card_issuer_country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("card_issuer_country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("card_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("card_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("currency_amount")
                        .HasColumnType("float");

                    b.Property<double>("currency_rate")
                        .HasColumnType("float");

                    b.Property<string>("currency_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("emi_amount")
                        .HasColumnType("float");

                    b.Property<string>("emi_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emi_instalment")
                        .HasColumnType("int");

                    b.Property<string>("emi_issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gw_version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("risk_level")
                        .HasColumnType("int");

                    b.Property<string>("risk_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("store_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tran_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("tran_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("val_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("validated_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("value_a")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value_b")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value_c")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value_d")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("reff_id");

                    b.ToTable("Application_Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
