// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Payment_Module.DiuSac
{
    public partial class Student
    {
        public Student()
        {
            Application = new HashSet<Application>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string ProgramId { get; set; }
        public string FacultyId { get; set; }
        public string CampusId { get; set; }
        public string ShiftId { get; set; }
        public string SemesterId { get; set; }
        public string MentorId { get; set; }
        public string FatherMobile { get; set; }
        public string LocalGuardianMobile { get; set; }
        public string PassOutSemester { get; set; }

        public virtual ICollection<Application> Application { get; set; }
    }
}